### ISSUE TITLE
Breaks CodeSpaces 🤷‍♂️ 

### ISSUE THREAD

**Issue by eddiejaoude** [eddiejaoude/dotfiles#1]
No logs available 😞

**Comment by rajneesh-18** [comment]
Did you solve this bug?

**Comment by eddiejaoude** [comment]
Probably not, but i don't use Codespaces anymore, so i think this can be closed and reopened later if needed. thank you @rajneesh-18 👍

**Comment by rajneesh-18** [comment]
It's my pleasure @eddiejaoude
