### ISSUE TITLE
Installation for linux/ubuntu os

### ISSUE THREAD

**Issue by MallikarjunHt** [eddiejaoude/dotfiles#2]
# installation 
Need script and command on how to install these on Linux ❤️ 
> Much Needed.

Thanks 😄

**Comment by eddiejaoude** [comment]
Not sure what you mean, something like this? https://ubuntu.com/tutorials/install-ubuntu-desktop#1-overview

**Comment by eddiejaoude** [comment]
In the `README.md` there is the quickstart. I realise it says Mac, but it is the same for linux https://github.com/eddiejaoude/dotfiles#quickstart

I will update it

**Comment by MallikarjunHt** [comment]
It works, thanks. :+1:
