### ISSUE TITLE
Add Virtualbox to the installation (optional)

### ISSUE THREAD

**Issue by eddiejaoude** [eddiejaoude/dotfiles#3]

**Comment by rajneesh-18** [comment]
Can you elaborate on the cause of this problem?

**Comment by eddiejaoude** [comment]
I think this is very old, i don't use VirtualBox anymore, so i will close - thank you or bringing it to my attention @rajneesh-18 👍

**Comment by rajneesh-18** [comment]
It's @eddiejaoude.
